config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users, only: [:show, :edit, :update]
resources :toys do
  get :toysnologin
	resource :toyfavorites, only: [:create, :destroy]
	resources :reviews do
    get :myreview
		resource :reviewfavorites, only: [:create, :destroy]
		collection do
      		post :confirm
    	end
    end
end
resources :genres, only: [:new, :index, :create, :edit, :update]
resources :children, only: [:index, :show, :new, :create, :edit, :update]
resources :child_archives, only: [:index, :show, :new, :create, :edit, :update]
resources :effects, only: [:new, :index, :create, :edit, :update]
resources :temperaments, only: [:new, :create, :edit, :update, :index]

get 'homes/about'
root 'homes#top'


end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/child.rb
class Child < ApplicationRecord

belongs_to :user
attachment :profile_image
has_many :child_archives, dependent: :destroy
accepts_nested_attributes_for :child_archives
has_many :child_temperaments, dependent: :destroy
has_many :temperaments, through: :child_temperaments
accepts_nested_attributes_for :child_temperaments, allow_destroy: true
has_many :reviews, dependent: :destroy

validates :name, presence: true
validates :sex, presence: true
validates :age_year, presence: true, numericality: { only_integer: true }
validates :age_month, presence: true, numericality: { only_integer: true }
validates :temperament_ids, presence: true
validates :favorite_thing, presence: true
validates :un_favorite_thing, presence: true
validates :status, presence: true


def self.search(search)
    if search
       where(['name LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
    else
       all #全て表示させる
    end
end

default_scope -> { order(created_at: :desc) }


end

app/models/child_archive.rb
class ChildArchive < ApplicationRecord
	attachment :profile_image
	belongs_to :child
	belongs_to :user
	has_many :child_archive_temperaments, dependent: :destroy
	has_many :temperaments, through: :child_archive_temperaments
	accepts_nested_attributes_for :child_archive_temperaments, allow_destroy: true

	validates :age_year, presence: true, numericality: { only_integer: true }
	validates :age_month, presence: true, numericality: { only_integer: true }
	validates :name, presence: true
	validates :favorite_thing, presence: true
	validates :un_favorite_thing, presence: true
	validates :status, presence: true



	def self.search(search)
	    if search
	       where(['name LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
	    else
	       all #全て表示させる
	    end
 	end

 	default_scope -> { order(created_at: :desc) }



end

app/models/destroy.rb
class Destroy < ApplicationRecord
end

app/models/effect.rb
class Effect < ApplicationRecord
	has_many :reviews, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
  	belongs_to :toy
  	belongs_to :effect
  	belongs_to :child
  	has_many :reviewfavorites, dependent: :destroy
    has_many :liked_reviews, through: :reviewfavorites, source: :user
    has_many :review_temperaments, dependent: :destroy
    has_many :temperaments, through: :review_temperaments
    accepts_nested_attributes_for :review_temperaments, allow_destroy: true


    validates :body, presence: true
    validates :effect_id, presence: true
    validates :rate, presence: true
    validates :age_year, presence: true
    validates :age_month, presence: true


	def reviewfavorited_by?(user)
    reviewfavorites.where(user_id: user.id).exists?
  end


  	validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true

  default_scope -> { order(created_at: :desc) }

end

app/models/reviewfavorite.rb
class Reviewfavorite < ApplicationRecord

	belongs_to :user
	belongs_to :review

end

app/models/temperament.rb
class Temperament < ApplicationRecord
	has_many :child_temperaments
	has_many :children, through: :child_temperaments
	has_many :child_archive_temperaments
	has_many :child_archives, through: :child_archive_temperaments
	has_many :review_temperaments
	has_many :reviews, through: :review_temperaments

end

app/models/toy.rb
class Toy < ApplicationRecord
	attachment :toy1_image
	attachment :toy2_image
	attachment :toy3_image
	attachment :toy4_image
	belongs_to :genre
	has_many :reviews, dependent: :destroy
	has_many :toyfavorites, dependent: :destroy
	has_many :liked_toys, through: :toyfavorites, source: :user

	def toyfavorited_by?(user)
    toyfavorites.where(user_id: user.id).exists?
  	end


	def self.search(search)
	    if search
	       where(['name LIKE ? OR manufacturer LIKE ? OR material LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
	    else
	       all #全て表示させる
	    end
 	end

end

app/models/toyfavorite.rb
class Toyfavorite < ApplicationRecord

	belongs_to :user
	belongs_to :toy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  validates :place, presence: true
  validates :sex, presence: true
  validates :email, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :children, dependent: :destroy
  has_many :child_archives, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :toyfavorites, dependent: :destroy
  has_many :liked_toys, through: :toyfavorites, source: :toy
  has_many :reviewfavorites, dependent: :destroy
  has_many :liked_reviews, through: :reviewfavorites, source: :review





end

app/controllers/toys_controller.rb
class ToysController < ApplicationController

  def new
    @toy = Toy.new
  end

  def create
    @toy = Toy.new(toy_params)
    if @toy.save
      redirect_to toy_path(@toy), notice: "追加完了"
    else
      @toy = Toy.new
      render "new"
    end
  end

  def show
    @toy = Toy.find(params[:id])

  end

  def index
    @toys = Toy.paginate(page: params[:page], per_page: 20).search(params[:search])
    @user = current_user
  end

  def edit
     @toy = Toy.find(params[:id])
  end

  def update
    @toy = Toy.find(params[:id])
    if @toy.update(toy_params)
      redirect_to toy_path(@toy), notice: "更新完了"
    else
      @toy = Toy.find(params[:id])
      render "edit"
    end
  end

  def toysnologin
     @toys = Toy.paginate(page: params[:page], per_page: 20).search(params[:search])
  end


  def destroy
  end


  private
  def toy_params
    params.require(:toy).permit(:name, :price, :manufacturer, :genre_id, :toy_image, :toy_introduction, :depth, :width, :height, :target_age, :material)
  end

end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/toys/create.html.erb
<h1>Toys#create</h1>
<p>Find me in app/views/toys/create.html.erb</p>

app/views/toys/edit.html.erb
<h1>おもちゃ情報編集</h1>


 <%= form_for(@toy) do |f| %>
  <table>
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <%= f.attachment_field :toy_image, placeholder: "Image", class: "user-edit-form" %>
        </td>
      </tr>
      <tr>
        <td>商品名</td>
        <td><%= f.text_field :name %></td>
        <td></td>
      </tr>
      <tr>
        <td>メーカー</td>
        <td><%= f.text_field :manufacturer %></td>
        <td></td>
      </tr>
      <tr>
        <td>素材</td>
        <td><%= f.text_field :material %></td>
        <td></td>
      </tr>
      <tr>
        <td>商品の寸法(奥行きx幅x高さ)</td>
        <td><%= f.text_field :depth %><%= "x" %></td>
        <td><%= f.text_field :width %><%= "x" %></td>
        <td><%= f.text_field :height %></td>
      </tr>
      <tr>
        <td>対象年齢</td>
        <td><%= f.text_area :target_age %><%= "歳から" %></td>
      </tr>
      <tr>
        <td>商品説明</td>
        <td><%= f.text_area :toy_introduction %></td>
      </tr>
      <tr>
        <td>ジャンル</td>
        <td><%= f.select :genre_id, Genre.all.map{ |genre| [genre.name, genre.id]} %></td>
      </tr>
      <tr>
        <td>価格</td>
        <td><%= f.text_field :price %>円</td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td><%= f.submit "新規登録", class: "btn-sm btn-primary" %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/toys/index.html.erb
<%= render 'layouts/header' %>

<div class="container">
<div class="breadcrumbs">
	<%= link_to root_path do %>
		<%= "Home" %>
	<% end %>
	<%= ">" %>
	<span class="current">商品一覧</span>
</div>


	<h3 class="toy_select">口コミする商品をお選び下さい</h3><br>

		<div class="col-md-12 searchfield">

			<%= form_tag(toys_path, :method => "get") do %>
			 <%= text_field_tag :search, '', placeholder: 'キーワードを入力して下さい' %>
			<%= submit_tag "検索" ,:name => nil ,class: "btn button is-info"%>
			<% end %>
		</div>

		<div class="col-md-12 searchfield">

			<br><br><br>

			<div class ="row toyindexrow">
				<% @toys.each do |toy| %>
				<div class="col-md-3 toy-index">
					<div class="panel panel-default">

						<div class="panel-heading text-center">
							<%= link_to toy_path(toy.id) do %>
							<%= attachment_image_tag toy, :toy1_image, format: 'jpeg', size: "200x200", fallback: "no_image.jpg" %>
							<% end %>
						</div>

						<div class="panel-body">
							<p class="product-brand"><%= toy.manufacturer %></p>
							<p class="product-title">
								<%= link_to toy_path(toy.id) do %>
									<%= toy.name %>
								<% end %>
							</p>
								<div id="star-rate-<%= toy.id %>"></div>
									<p class="product-review">口コミ
										<%= link_to toy_path(toy.id) do %>
											<%= toy.reviews.count %>
										<% end %>
								件 &nbsp;
									</p>
							<script>
								$('#star-rate-<%= toy.id %>').raty({
									size: 36,
							        starOff:  '<%= asset_path('star-off.png') %>',
							        starOn : '<%= asset_path('star-on.png') %>',
							        starHalf: '<%= asset_path('star-half.png') %>',
							        half: true,
							        readOnly: true,
							        score: <%= toy.reviews.average(:rate).to_f.round(1) %>,
							    });
							</script>
							<%= toy.reviews.average(:rate).to_f.round(1) %>点<br>
							<%= link_to '口コミする',  new_toy_review_path(toy), class: 'btn btn-primary botan', data: {"turbolinks" => false} %>
						</div>

						<% if user_signed_in? %>
						<div class="panel-footer">

								<% if toy.toyfavorited_by?(current_user) %>
				                  <%= link_to toy_toyfavorites_path(toy), method: :delete do %>
				                  	<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
				                  <% end %>
				                <% else %>
				                  <%= link_to toy_toyfavorites_path(toy), method: :post do %>
				                  	<i class="far fa-heart"></i>
				                  <% end %>
								<% end %>
								  <%= toy.toyfavorites.count %>
						</div>
						<% end %>
					</div>
				</div>
				<% end %>
			</div>
		</div>
</div>

app/views/toys/new.html.erb
<h1>おもちゃ情報登録</h1>

 <%= form_for(@toy) do |f| %>
  <%= f.attachment_field :toy_image %>
  <table>
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>商品名</td>
        <td><%= f.text_field :name %></td>
        <td></td>
      </tr>
      <tr>
        <td>メーカー</td>
        <td><%= f.text_field :manufacturer %></td>
        <td></td>
      </tr>
      <tr>
        <td>素材</td>
        <td><%= f.text_field :material %></td>
        <td></td>
      </tr>
      <tr>
        <td>商品の寸法(奥行きx幅x高さ)</td>
        <td><%= f.text_field :depth %><%= "x" %></td>
        <td><%= f.text_field :width %><%= "x" %></td>
        <td><%= f.text_field :height %></td>
      </tr>
      <tr>
        <td>対象年齢</td>
        <td><%= f.text_area :target_age %><%= "歳から" %></td>
      </tr>
      <tr>
        <td>商品説明</td>
        <td><%= f.text_area :toy_introduction %></td>
      </tr>
      <tr>
        <td>ジャンル</td>
        <td><%= f.select :genre_id, Genre.all.map{ |genre| [genre.name, genre.id]} %></td>
      </tr>
      <tr>
        <td>価格</td>
        <td><%= f.text_field :price %>円</td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td><%= f.submit "新規登録", class: "btn-sm btn-primary" %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/toys/show.html.erb
<%= render 'layouts/header' %>

<div class="container">
	<div class="row col-md-offset-4 col-md-8 reviewnewtitle">
	    <h4 style= "font-size: 25px"><%= @toy.manufacturer %>  <%= @toy.name %></h4>
    </div>

    <div class="row">

		    <div class="col-md-offset-1 col-md-4 reviewnewtitle">

		    	<div class="a">
				    <div class="b"><%= attachment_image_tag @toy, :toy1_image, format: 'jpeg', size: "300x300" %></div>
				    <div class="b"><%= attachment_image_tag @toy, :toy2_image, format: 'jpeg', size: "300x300" %></div>
				    <div class="b"><%= attachment_image_tag @toy, :toy3_image, format: 'jpeg', size: "300x300" %></div>
				</div>

		    	<br>

				<% if user_signed_in? %>
						<div class="toy-index-favorite">

								<% if @toy.toyfavorited_by?(current_user) %>
				                  <%= link_to toy_toyfavorites_path(@toy), method: :delete do %>
				                  	<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
				                  <% end %>
				                <% else %>
				                  <%= link_to toy_toyfavorites_path(@toy), method: :post do %>
				                  	<i class="far fa-heart"></i>
				                  <% end %>
								<% end %>
								  <%= @toy.toyfavorites.count %>
						</div>
						<% end %>

			</div>

			<div class="col-md-7">

				<table class="table toytable">
					<tbody>
						<tr>
			  				<th class="active">詳細情報</th>
			  				<th><%= @toy.name %></th>
		  				</tr>
		  				<tr>
			  				<th class="active">メーカー</th>
					        <th><%= @toy.manufacturer %></th>
				      	</tr>
				      	<tr>
			  				<th class="active">商品名</th>
					        <th><%= @toy.name %></th>
				      	</tr>
				      	<tr>
			  				<th class="active">アイテムジャンル</th>
					        <th><%= @toy.genre.name %></th>
				      	</tr>
				      	<tr>
			  				<th class="active">価格</th>
					        <th><%= @toy.price %></th>
				      	</tr>
				      	<tr>
			  				<th class="active">素材</th>
					        <th><%= @toy.material %></th>
				      	</tr>
				        <tr>
					        <th class="active">商品の寸法(奥行きx幅x高さ)</th>
					        <th><%= @toy.depth %><%= "x" %>
					        <%= @toy.width %><%= "x" %>
				        	<%= @toy.height %></th>
				      	</tr>
				      　<tr>
					        <th class="active">対象年齢</th>
					        <th><%= @toy.target_yearage %><%= "歳" %>
					        	<%= @toy.target_monthage %><%= "歳ヶ月〜" %>
					        </th>
				      　</tr>
		  				<tr>
			  				<th class="active">商品説明</th>
			  				<th><%= @toy.toy_introduction %></th>
		  				</tr>
					</tbody>
				</table>
			</div>
	</div>
<br><br>

	<div class="col-md-12 searchfield">

		<% @toy.reviews.each do |review| %>

						<div class="reviewarea">
							<div class="col-md-2 review-user">
								<%= attachment_image_tag review.user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %><br>
								<p><%= review.user.name %>さん</p>
							</div>
							<div class="col-md-10 review-toy">
								<div class="reviewscontent">
									<div class="reviewscontenthead">
										<p class="reviewday" style="font-size: 10px"><%= review.created_at.strftime('%Y/%m/%d') %></p>
										<span style="font-size: 10px">使用したお子様の情報:　</span>
										<% if review.child.sex == 1 %>
											<%= "男の子 " %><i class="fas fa-male " style="color: #68a4d9"></i>   |
										<% else %>
											<%= "女の子 " %><i class="fas fa-female" style="color: #e95388"></i>   |
										<% end %>
										<%= review.age_year %>歳<%= review.age_month %>ヶ月     |
										<%= review.temperaments.pluck(:name).join(" ・") %>
									</div><br>
									<div class="col-md-4 reviewstoy">
										<%= link_to toy_path(review.toy.id) do %>
											<%= attachment_image_tag review.toy, :toy1_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %><br>
										<% end %>
										<p style="font-size: 10px"><%= review.toy.name %></p><br>
									</div>
									<div class="col-md-8">
									<%= review.rate %>点
						         		<!--星評価-->
								         <div id="star-rate-<%= review.id %>"></div>
								          <script>
								          $('#star-rate-<%= review.id %>').raty({
								            size: 36,
								            starOff:  '<%= asset_path('star-off.png') %>',
								            starOn : '<%= asset_path('star-on.png') %>',
								            starHalf: '<%= asset_path('star-half.png') %>',
								            half: true,
								            readOnly: true,
								            score: <%= review.rate %>,
								          });
								          </script>
				        				<!--/星評価-->





				        				<br><br><p style="font-size: 10px"><%= review.body.truncate(30) %></p><br>


				        				<%= link_to '詳しくみる', toy_review_path(review.toy, review), class: 'btn btn-primary col-md-offset-2 col-md-6', data: {"turbolinks" => false} %>

				        				<% if user_signed_in? %>
										<% unless review.user == current_user %>
											<% if review.reviewfavorited_by?(current_user) %>
											  <%= link_to toy_review_reviewfavorites_path(review.toy, review), method: :delete do %>
											   参考になった！<i class="fas fa-thumbs-up"></i>
											    <%= review.reviewfavorites.count %>
											  <% end %>
											<% else %>
											  <%= link_to toy_review_reviewfavorites_path(review.toy, review), method: :post do %>
											   参考になった！<i class="far fa-thumbs-up"></i>
											    <%= review.reviewfavorites.count %>
											  <% end %>
											<% end %>
										<% else %>
											参考になった！<i class="fas fa-thumbs-up"></i><%= review.reviewfavorites.count %>
										<% end %>
										<% end %>

									</div>
								</div>
							</div>
						</div>
		<% end %>

app/views/toys/toysnologin.html.erb
<%= render 'layouts/header' %>

<div class="container">
<div class="breadcrumbs">
	<%= link_to root_path do %>
		<%= "Home" %>
	<% end %>
	<%= ">" %>
	<span class="current">商品一覧</span>
</div>


	<h3 class="toy_select">見たい口コミの商品をお選び下さい</h3><br>

		<div class="col-md-12 searchfield">

			<%= form_tag(toys_path, :method => "get") do %>
			 <%= text_field_tag :search, '', placeholder: 'キーワードを入力して下さい' %>
			<%= submit_tag "検索" ,:name => nil ,class: "btn button is-info"%>
			<% end %>
		</div>

		<div class="col-md-12 searchfield">

			<br><br><br>

			<div class ="row toyindexrow">
				<% @toys.each do |toy| %>
				<div class="col-md-3 toy-index">
					<div class="panel panel-default">

						<div class="panel-heading text-center">
							<%= link_to toy_path(toy.id) do %>
							<%= attachment_image_tag toy, :toy1_image, format: 'jpeg', size: "200x200", fallback: "no_image.jpg" %>
							<% end %>
						</div>

						<div class="panel-body">
							<p class="product-brand"><%= toy.manufacturer %></p>
							<p class="product-title">
								<%= link_to toy_path(toy.id) do %>
									<%= toy.name %>
								<% end %>
							</p>
								<div id="star-rate-<%= toy.id %>"></div>
									<p class="product-review">口コミ
										<%= link_to toy_path(toy.id) do %>
											<%= toy.reviews.count %>
										<% end %>
								件 &nbsp;
									</p>
							<script>
								$('#star-rate-<%= toy.id %>').raty({
									size: 36,
							        starOff:  '<%= asset_path('star-off.png') %>',
							        starOn : '<%= asset_path('star-on.png') %>',
							        starHalf: '<%= asset_path('star-half.png') %>',
							        half: true,
							        readOnly: true,
							        score: <%= toy.reviews.average(:rate).to_f.round(1) %>,
							    });
							</script>
							<%= toy.reviews.average(:rate).to_f.round(1) %>点<br>
						</div>

					</div>
				</div>
				<% end %>
			</div>
		</div>
</div>