config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users, only: [:show, :edit, :update]
resources :toys do
  get :toysnologin
	resource :toyfavorites, only: [:create, :destroy]
	resources :reviews do
    get :myreview
		resource :reviewfavorites, only: [:create, :destroy]
		collection do
      		post :confirm
    	end
    end
end
resources :genres, only: [:new, :index, :create, :edit, :update]
resources :children, only: [:index, :show, :new, :create, :edit, :update]
resources :child_archives, only: [:index, :show, :new, :create, :edit, :update]
resources :effects, only: [:new, :index, :create, :edit, :update]
resources :temperaments, only: [:new, :create, :edit, :update, :index]

get 'homes/about'
root 'homes#top'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  validates :place, presence: true
  validates :sex, presence: true
  validates :email, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :children, dependent: :destroy
  has_many :child_archives, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :toyfavorites, dependent: :destroy
  has_many :liked_toys, through: :toyfavorites, source: :toy
  has_many :reviewfavorites, dependent: :destroy
  has_many :liked_reviews, through: :reviewfavorites, source: :review





end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

def after_sign_up_path_for(resource)
    flash[:notice] = "会員登録が完了しました！"
    new_child_path
end


end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = current_user
    @reviews = Reviewfavorite.where(review_id: current_user.reviews.ids)
    @review = @user.reviews.all.order('created_at DESC').limit(1)
    @child_archives = @user.child_archives.all.limit(2)
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
     redirect_to user_path(current_user.id), alert: "不正なアクセスです"
    end
  end

  def update
    @user = User.find(params[:id])
    if
      @user.update(user_params)
      flash[:notice] = "プロフィールを更新しました"
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :place, :hobby, :sex, :age, :email)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'layouts/header' %>

<div class="container">

<div class="breadcrumbs">
<%= link_to root_path do %>
<%= "Home" %>
  <% end %>
  <%= ">" %>
  <span class="current">登録情報編集</span>
</div>

<div class="container">



<h1>登録情報編集</h1>

<table class="table form-group">
                    <tbody>
                      <%= form_for(@user) do |f| %>
                        <tr>
                          <td>
                            <%= f.attachment_field :profile_image, placeholder: "Image", class: "user-edit-form" %>
                          </td>
                        </tr>

                        <tr>
                          <td>ニックネーム</td>
                          <td>
                            <%= f.text_field :name, autofocus: true %>
                          </td>
                        </tr>
                        <tr>
                            <td>お住まいの都道府県</td>
                            <td><%= f.text_field :place, autofocus: true %></td>
                        </tr>
                        <tr>
                            <td>性別</td>
                            <td>
                            <%= f.select :sex, {'男性': 1, '女性': 2}, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
                            </td>
                        </tr>
                        <tr>
                            <td>ご年齢</td>
                            <td>
                           <%= f.text_field :age, autofocus: true %><%="歳"%>
                            </td>
                        </tr>
                        <tr>
                            <td>メールアドレス</td>
                            <td><%= f.text_field :email %></td>
                        </tr>
                        <tr>
                            <td>ご趣味</td>
                            <td><%= f.text_field :hobby %></td>
                        </tr>
                        <tr>
                            <td>自己紹介</td>
                            <td><%= f.text_field :introduction %></td>
                        </tr>
                        <tr>
                          <td><%= f.submit "変更を保存する", class: "btn-sm btn-primary" %></td>
                            <td></td>
                        </tr>
                      <% end %>
                    </tbody>
        </table>
</div>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<div class="container">

  <div class="breadcrumbs">
    <%= link_to root_path do %>
      <%= "Home" %>
    <% end %>
    <%= ">" %>
    <span class="current">マイページ</span>
  </div>



  <h3 class="toy_select">マイページ</h3><br>

  <div class="row">
    <div class="col-md-3">
      <div class="prof-area">

        <%= render 'layouts/profile', user: @user %>
        <%= link_to '編集する', edit_user_path(@user), class: 'btn btn-primary col-md-offset-2 col-md-6', data: {"turbolinks" => false} %><br>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="mypagetitle">
          <h4><%= @user.name %>さんの最近の口コミ</h4>
        </div>
        <% if @review.present? %>
          <% @review.each do |review| %>
            <div>
              <div class="mypagecontent">
                <div class="col-md-12 review-toy">
                  <div class="reviewscontent">
                    <div class="reviewscontenthead">
                      <p class="reviewday"><%= review.created_at.strftime('%Y/%m/%d') %></p>
                        <p class="mypagereview">使用したお子様の情報:
                          <%= review.child.name %>  ｜
                          <%= review.age_year %>歳  <%= review.age_month %>ヶ月  |
                          <%= review.temperaments.pluck(:name).join(",") %>
                        </p>
                    </div><br>
                    <div class="col-md-5 reviewstoy">
                      <%= link_to toy_path(review.toy.id) do %>
                      <%= attachment_image_tag review.toy, :toy1_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
                      <br>
                      <% end %>
                      <p class="mypagereview">
                      <%= link_to toy_path(review.toy.id) do %>
                        <%= review.toy.name %></p>
                      <% end %>
                      <br>
                    </div>
                    <div class="col-md-7 mypagereviewcontain">
                      <!--星評価-->
                      <div id="star-rate-<%= review.id %>"><%= review.rate %><%="　"%></div>
                        <script>
                          $('#star-rate-<%= review.id %>').raty({
                          size: 36,
                          starOff:  '<%= asset_path('star-off.png') %>',
                          starOn : '<%= asset_path('star-on.png') %>',
                          starHalf: '<%= asset_path('star-half.png') %>',
                          half: true,
                          readOnly: true,
                          score: <%= review.rate %>,
                          });
                        </script>
                      <!--/星評価-->
                        <br><br><br><%= review.body.truncate(30) %><br><br>
                      </div>
                      <div class="centerbtn">
                        <%= link_to '詳しく見る', toy_review_myreview_path(1,1), class: 'btn btn-primary', data: {"turbolinks" => false} %>
                      </div>
                    </div>
                  </div>
                  <div class="centerbtn">
                    <%= link_to 'もっと見る', toy_review_myreview_path(review.toy, review), class: 'btn btn-primary', data: {"turbolinks" => false} %>
                  </div>
                </div>
　　　　　　　　</div>
　　　　　　　<% end %>
          <% else %>
            <div class="mypagecontent">
              <div class="col-md-12 mypagenocontants">
                <p>投稿した口コミはありません。</p>
              </div>
            </div>
          <% end %>
        </div>

        <div class="row">
          <div class="mypagetitle">
            <h4>いいねした商品</h4>
          </div>

        <div>
          <div class="mypagecontent">

            <% if @user.liked_toys.present? %>
              <% @user.liked_toys.each do |toy| %>
                <div class="col-md-3 mypagetoyfavorite">
                  <div class="panel panel-default">

                    <div class="panel-heading text-center">
                      <%= link_to toy_path(toy.id) do %>
                        <%= attachment_image_tag toy, :toy1_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
                      <% end %>
                    </div>

                    <div class="panel-body">
                      <p class="product-brand"><%= toy.manufacturer %></p>
                      <p class="toyfavorite-title">
                      <%= link_to toy_path(toy.id) do %>
                        <%= toy.name %>
                      <% end %>
                      </p>
                    </div>

                    <div class="mypage-panel-footer">

                      <% if toy.toyfavorited_by?(current_user) %>
                        <%= link_to toy_toyfavorites_path(toy), method: :delete do %>
                          <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                        <% end %>
                      <% else %>
                        <%= link_to toy_toyfavorites_path(toy), method: :post do %>
                          <i class="far fa-heart"></i>
                        <% end %>
                      <% end %>
                        <%= toy.toyfavorites.count %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div>
                <div class="mypagecontent">
                  <div class="col-md-12 mypagenocontants">
                    <p>いいねしたおもちゃはありません。</p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="mypagetitle">
          <h4>いいねした口コミ</h4>
        </div>

        <div>
          <div class="mypagecontent">
            <% if @user.liked_reviews.present? %>
              <% @user.liked_reviews.each do |review| %>
                <div>
                  <div class="col-md-2 review-user">
                    <%= attachment_image_tag review.user, :profile_image, format: 'jpeg', size: "70x70", fallback: "no_image.jpg" %><br>
                    <%= review.user.name %>さん
                  </div>
                  <div class="col-md-10 review-toy">
                    <div class="reviewscontent">
                      <div class="reviewscontenthead">
                        <p class="toyfavorite-title"><%= review.created_at.strftime('%Y/%m/%d') %></p>
                        使用したお子様の情報:
                        <%= review.age_year %>歳<%= review.age_month %>ヶ月 |
                        <%= review.child.temperaments.pluck(:name).join(",") %>
                      </div><br>
                      <div class="col-md-4 toyfavorite-title">
                        <%= link_to toy_path(review.toy.id) do %>
                        <%= attachment_image_tag review.toy, :toy1_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %><br>
                      <% end %>
                      <%= link_to toy_path(review.toy.id) do %>
                        <%= review.toy.name %><br>
                      <% end %>
                      </div>
                      <div class="col-md-8 mypagefavoritereview">
                        <!--星評価-->
                        <div id="star-rate-<%= review.id %>"><%= review.rate %><%="　"%></div>
                          <script>
                            $('#star-rate-<%= review.id %>').raty({
                            size: 36,
                            starOff:  '<%= asset_path('star-off.png') %>',
                            starOn : '<%= asset_path('star-on.png') %>',
                            starHalf: '<%= asset_path('star-half.png') %>',
                            half: true,
                            readOnly: true,
                            score: <%= review.rate %>,
                            });
                          </script>
                        <!--/星評価-->
                        <br><br><%= review.body.truncate(30) %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div class="mypagecontent">
                <div class="col-md-12 mypagenocontants">
                  <p>いいねした口コミはありません。</p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="row right-sidebar">
        <h4 class="mypagetitle">登録済みのお子様</h4>
        <% if @user.children.present? %>
          <% @user.children.last(2).each do |child| %>
            <div class="mypagechild">
              <%= link_to edit_child_path(child.id) do %>
                <%= attachment_image_tag child, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
              <% end %>
              <%= child.name %><br>
              <%= child.temperaments.pluck(:name).join("/") %>
            </div>
          <% end %>
          <%= link_to 'もっと見る', children_path(@user), class: 'btn btn-primary col-md-offset-3 col-md-6', data: {"turbolinks" => false} %>
          <%= link_to 'お子様を登録する', new_child_path, class: 'btn btn-primary col-md-offset-3 col-md-6', data: {"turbolinks" => false} %>
        <% else %>
          <div>
            <div class="mypagecontent">
              <div class="col-md-12 mypagenocontants">
                <p>登録がまだありません。</p>
              </div>
            </div>
            <%= link_to 'お子様を登録する', new_child_path, class: 'btn btn-primary col-md-offset-3 col-md-6', data: {"turbolinks" => false} %>
          </div>
        <% end %>
      </div>

      <br>
      <br>

      <div class="row right-sidebar">
        <h4 class="mypagetitle">最近のおもいで</h4>

        <% if @child_archives.present? %>
          <% @child_archives.each do |child_archive| %>
            <div class="mypagechild">
              <%= link_to child_archive_path(child_archive.id) do %>
                <%= attachment_image_tag child_archive, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
              <% end %>
              <%= child_archive.created_at.strftime('%Y/%m/%d') %><br>
              <%= child_archive.child.name %><br>
            </div>
          <% end %>
          <%= link_to 'もっと見る', child_archives_path(@user), class: 'btn btn-primary col-md-offset-3 col-md-6', data: {"turbolinks" => false} %>
        <% else %>
          <div class="mypagecontent">
            <div class="col-md-12 mypagenocontants">
              <p>登録がまだありません。</p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>