config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users, only: [:show, :edit, :update]
resources :toys do
  get :toysnologin
	resource :toyfavorites, only: [:create, :destroy]
	resources :reviews do
    get :myreview
		resource :reviewfavorites, only: [:create, :destroy]
		collection do
      		post :confirm
    	end
    end
end
resources :genres, only: [:new, :index, :create, :edit, :update]
resources :children, only: [:index, :show, :new, :create, :edit, :update]
resources :child_archives, only: [:index, :show, :new, :create, :edit, :update]
resources :effects, only: [:new, :index, :create, :edit, :update]
resources :temperaments, only: [:new, :create, :edit, :update, :index]

get 'homes/about'
root 'homes#top'


end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/child.rb
class Child < ApplicationRecord

belongs_to :user
attachment :profile_image
has_many :child_archives, dependent: :destroy
accepts_nested_attributes_for :child_archives
has_many :child_temperaments, dependent: :destroy
has_many :temperaments, through: :child_temperaments
accepts_nested_attributes_for :child_temperaments, allow_destroy: true
has_many :reviews, dependent: :destroy

validates :name, presence: true
validates :sex, presence: true
validates :age_year, presence: true, numericality: { only_integer: true }
validates :age_month, presence: true, numericality: { only_integer: true }
validates :temperament_ids, presence: true
validates :favorite_thing, presence: true
validates :un_favorite_thing, presence: true
validates :status, presence: true


def self.search(search)
    if search
       where(['name LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
    else
       all #全て表示させる
    end
end

default_scope -> { order(created_at: :desc) }


end

app/models/child_archive.rb
class ChildArchive < ApplicationRecord
	attachment :profile_image
	belongs_to :child
	belongs_to :user
	has_many :child_archive_temperaments, dependent: :destroy
	has_many :temperaments, through: :child_archive_temperaments
	accepts_nested_attributes_for :child_archive_temperaments, allow_destroy: true

	validates :age_year, presence: true, numericality: { only_integer: true }
	validates :age_month, presence: true, numericality: { only_integer: true }
	validates :name, presence: true
	validates :favorite_thing, presence: true
	validates :un_favorite_thing, presence: true
	validates :status, presence: true



	def self.search(search)
	    if search
	       where(['name LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
	    else
	       all #全て表示させる
	    end
 	end

 	default_scope -> { order(created_at: :desc) }



end

app/models/destroy.rb
class Destroy < ApplicationRecord
end

app/models/effect.rb
class Effect < ApplicationRecord
	has_many :reviews, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
  	belongs_to :toy
  	belongs_to :effect
  	belongs_to :child
  	has_many :reviewfavorites, dependent: :destroy
    has_many :liked_reviews, through: :reviewfavorites, source: :user
    has_many :review_temperaments, dependent: :destroy
    has_many :temperaments, through: :review_temperaments
    accepts_nested_attributes_for :review_temperaments, allow_destroy: true


    validates :body, presence: true
    validates :effect_id, presence: true
    validates :rate, presence: true
    validates :age_year, presence: true
    validates :age_month, presence: true


	def reviewfavorited_by?(user)
    reviewfavorites.where(user_id: user.id).exists?
  end


  	validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true

  default_scope -> { order(created_at: :desc) }

end

app/models/reviewfavorite.rb
class Reviewfavorite < ApplicationRecord

	belongs_to :user
	belongs_to :review

end

app/models/temperament.rb
class Temperament < ApplicationRecord
	has_many :child_temperaments
	has_many :children, through: :child_temperaments
	has_many :child_archive_temperaments
	has_many :child_archives, through: :child_archive_temperaments
	has_many :review_temperaments
	has_many :reviews, through: :review_temperaments

end

app/models/toy.rb
class Toy < ApplicationRecord
	attachment :toy1_image
	attachment :toy2_image
	attachment :toy3_image
	attachment :toy4_image
	belongs_to :genre
	has_many :reviews, dependent: :destroy
	has_many :toyfavorites, dependent: :destroy
	has_many :liked_toys, through: :toyfavorites, source: :user

	def toyfavorited_by?(user)
    toyfavorites.where(user_id: user.id).exists?
  	end


	def self.search(search)
	    if search
	       where(['name LIKE ? OR manufacturer LIKE ? OR material LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
	    else
	       all #全て表示させる
	    end
 	end

end

app/models/toyfavorite.rb
class Toyfavorite < ApplicationRecord

	belongs_to :user
	belongs_to :toy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  validates :place, presence: true
  validates :sex, presence: true
  validates :email, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :children, dependent: :destroy
  has_many :child_archives, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :toyfavorites, dependent: :destroy
  has_many :liked_toys, through: :toyfavorites, source: :toy
  has_many :reviewfavorites, dependent: :destroy
  has_many :liked_reviews, through: :reviewfavorites, source: :review





end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :confirm, :create, :myreview]

  def new
    @toy = Toy.find(params[:toy_id])
    @review = current_user.reviews.new
    @children = current_user.children
  end

  def confirm
    @toy = Toy.find(params[:toy_id])
    @review = current_user.reviews.new(review_params)
  end

  def create
    @toy = Toy.find(params[:toy_id])
    @child = Child.find(params[:review][:child_id])
    @review = current_user.reviews.new(review_params)
    @review.toy_id = @toy.id
    @review.user_id = current_user.id
    @review.age_year = @child.age_year
    @review.age_month = @child.age_month
    review_params_temperament_ids.each do |temperament_id|
    @review.review_temperaments.build(temperament_id: temperament_id)
    end
    if  @review.save
        redirect_to toy_path(@toy)
        flash[:notice] = "口コミを投稿しました"
    else
        redirect_to new_toy_review_path
        flash[:notice] = "口コミが投稿できませんでした"
    end
  end

  def index
    @reviews = Review.all
  end

  def show
    @toy = Toy.find(params[:toy_id])
    @review = Review.find(params[:id])
  end


  def search
  @reviews = Review.search(params[:search])
  end

  def myreview
    @user = current_user
    @reviews = @user.reviews.all
  end


  private
  def review_params
    params.require(:review).permit(:body, :effect_id, :toy_id, :rate, :user_id, :child_id)
  end

  def review_params_temperament_ids
    params.require(:temperament_ids)
  end


end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/confirm.html.erb
<%= render 'layouts/header' %>

<div class="container">

  <div class="col-md-8 reviewnewtitle">
    <h3>口コミ内容確認</h3>
  </div>

  <br><br>

  <div class="row col-md-offset-3 col-md-8 reviewtoy">
    <div>
      <div class="col-md-3">
        <%= attachment_image_tag @toy, :toy1_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
      </div>

      <div class="col-md-5 reviewtoyp">
        <%= @toy.manufacturer %><br>
        <%= @toy.name %><br>
        <%= @toy.price %>円<br>
      </div>
    </div>
  </div>


  <div class="row col-md-12 reviewform">

    <div class="col-md-offset-2 col-md-8 reviewinform">

      <div class="col-md-12 revieweffect form-group">
        ご使用したお子様：<%= @review.child.name %><br>
        ご使用したお子様の特徴：<%= @review.child.temperaments.pluck(:name).join(",") %>
      </div>

      <div class="form-group row" id="star">
        オススメ度：
        <!-- 評価javascript -->
        <script>
          $('#star').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'review[rate]',
          half: true,
          readOnly: true,
          score: <%= @review.rate %>
          });
        </script>
        <%= @review.rate %>
      </div>

      <div class="col-md-12 revieweffect form-group">
        効果：<%= @review.effect.name %>
      </div>

      <div class="col-md-offset-2 col-md-8 form-group">
        <%= @review.body %>
      </div>


      <%= simple_form_for [@toy,@review] do |f| %>
        <%#= render 'layouts/error_messages', locals: { review: [@toy,@review] } %>
        <%= f.input :rate, as: :hidden %>
        <%= f.input :effect_id, as: :hidden %>
        <%= f.input :body, as: :hidden %>
        <%= f.input :child_id, as: :hidden %>
        <% @review.child.temperaments.each do |temp| %>
        <!-- <%= f.input :temperament_ids, value: @review.child.temperament_ids, as: :hidden %>-->
        <input type="hidden" name="temperament_ids[]" value="<%=temp.id %>">
        <% end %>


        <div class="actions col-md-offset-2 col-md-8">
          <%= f.submit '投稿する', class: "btn btn-lg btn-base-1 btn-success mt-20 botan" %><br>
          <%= link_to '投稿画面に戻る', new_toy_review_path, class: "btn btn-base-1 btn-sm botan" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<%= render 'layouts/header' %>

<div class="container">

  <div class="breadcrumbs">
    <%= link_to root_path do %>
  　　<%= "Home" %>
    <% end %>
    <%= ">" %>
    <span class="current">口コミ一覧</span>
  </div>


  <h3 class="toy_select">最近の口コミ</h3><br>

    <div class="col-md-12 searchfield">

      <% @reviews.each do |review| %>

        <div class="reviewarea">
          <div class="col-md-2 review-user">
            <%= attachment_image_tag review.user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %><br>
            <p><%= review.user.name %>さん</p>
          </div>
          <div class="col-md-10 review-toy">
            <div class="reviewscontent">
              <div class="reviewscontenthead">
                <p class="reviewday" style="font-size: 10px"><%= review.created_at.strftime('%Y/%m/%d') %></p>
                <span style="font-size: 10px">使用したお子様の情報:　</span>
                <% if review.child.sex == 1 %>
                  <%= "男の子 " %><i class="fas fa-male " style="color: #68a4d9"></i>   |
                <% else %>
                  <%= "女の子 " %><i class="fas fa-female" style="color: #e95388"></i>   |
                <% end %>
                <%= review.child.age_year %>歳<%= review.child.age_month %>ヶ月 |
                <%= review.temperaments.pluck(:name).join(" ・") %>
              </div>
              <br>
              <div class="col-md-4 reviewstoy">
                <%= link_to toy_path(review.toy.id) do %>
                  <%= attachment_image_tag review.toy, :toy1_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %><br>
                <% end %>
                <p style="font-size: 10px"><%= review.toy.name %></p><br>
              </div>
              <div class="col-md-8">
                <!--星評価-->
                <div id="star-rate-<%= review.id %>"><%= review.rate %><%="　"%></div>
                  <script>
                    $('#star-rate-<%= review.id %>').raty({
                    size: 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    half: true,
                    readOnly: true,
                    score: <%= review.rate %>,
                    });
                  </script>
                <!--/星評価-->
                <br><br><p style="font-size: 10px"><%= review.body.truncate(30) %></p><br><br>

                <%= link_to '詳しくみる', toy_review_path(review.toy, review), class: 'btn btn-primary col-md-offset-2 col-md-6', data: {"turbolinks" => false} %>

                <% if user_signed_in? %>
                  <% unless review.user == current_user %>
                    <% if review.reviewfavorited_by?(current_user) %>
                      <%= link_to toy_review_reviewfavorites_path(review.toy, review), method: :delete do %>
                          参考になった！<i class="fas fa-thumbs-up"></i>
                        <%= review.reviewfavorites.count %>
                      <% end %>
                    <% else %>
                      <%= link_to toy_review_reviewfavorites_path(review.toy, review), method: :post do %>
                        参考になった！<i class="far fa-thumbs-up"></i>
                        <%= review.reviewfavorites.count %>
                      <% end %>
                    <% end %>
                <% else %>
                    参考になった！<i class="fas fa-thumbs-up"></i><%= review.reviewfavorites.count %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
    </div>
    <% end %>
  </div>
</div>

app/views/reviews/myreview.html.erb
<%= render 'layouts/header' %>

<div class="container">

  <div class="breadcrumbs">
    <%= link_to root_path do %>
      <%= "Home" %>
    <% end %>
    <%= ">" %>
    <span class="current">MyReviews</span>
  </div>


  <h3 class="toy_select"><%= @user.name %>さん　の口コミ</h3><br>

  <div class="col-md-12 searchfield">

    <% @reviews.each do |review| %>

      <div class="reviewarea">
        <div class="col-md-12 review-toy">
          <div class="reviewscontent">
            <div class="reviewscontenthead">
              <p class="reviewday" style="font-size: 10px"><%= review.created_at.strftime('%Y/%m/%d') %></p>
              <span style="font-size: 10px">使用したお子様の情報:　</span>
              <%= review.child.name  %> |
              <%= review.child.age_year %>歳<%= review.child.age_month %>ヶ月 |
              <%= review.child.temperaments.pluck(:name).join(" ・") %>
            </div><br>
            <div class="col-md-4 reviewstoy">
              <%= link_to toy_path(review.toy.id) do %>
                <%= attachment_image_tag review.toy, :toy1_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %><br>
              <% end %>
              <%= review.toy.name %><br>
            </div>
            <div class="col-md-8">
              <!--星評価-->
              <div id="star-rate-<%= review.id %>"><%= review.rate %><%="　"%></div>
                <script>
                  $('#star-rate-<%= review.id %>').raty({
                  size: 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= review.rate %>,
                  });
                </script>
              <!--/星評価-->
              <br><br><%= review.body %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<%= render 'layouts/header' %>

<div class="container">


      <div class="col-md-8 reviewnewtitle">
        <h3>口コミを投稿する</h3>
      </div>

      <br><br>

        <div class="row col-md-offset-3 col-md-8 reviewtoy">
          <div>
            <div class="col-md-3">
              <%= attachment_image_tag @toy, :toy1_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
            </div>

            <div class="col-md-5 reviewtoyp">
              <%= @toy.manufacturer %><br>
              <%= @toy.name %><br>
              <%= @toy.price %>円<br>
            </div>
          </div>
        </div>


        <div class="row col-md-12 reviewform">

          <div class="col-md-offset-2 col-md-8 reviewinform">

                <%= form_for [@toy, @review], url: confirm_toy_reviews_path do |f| %>

                  <div class="col-md-12 revieweffect form-group">
                    <%= f.label :child_id,'使用したお子様', class:'col-form-label' %>
                    <%= f.select :child_id, @children.map{|c| [c.name, c.id]} %>
                  </div>

                  <!-- 評価 -->
                  <div class="form-group" id="star">
                    <%= f.label :rate,'オススメ度　　', class:'col-form-label' %>
                    <%= f.hidden_field :rate, id: :review_star %>
                  </div>

                  <!-- 評価javascript -->
                  <script>
                  $('#star').raty({
                    size     : 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    scoreName: 'review[rate]',
                    half: true,
                  });
                  </script>

                  <div class="col-md-12 revieweffect form-group">
                    <%= f.label :effect_id,'効果　　　', class:'col-form-label' %>
                    <%= f.select :effect_id, Effect.all.map{ |effect| [effect.name, effect.id]} %>
                  </div>
                  <div class="col-md-offset-2 col-md-9 form-group">
                    <%= f.text_area :body, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
                  </div>

                  <div class="col-md-12 revieweffect botan">
                    <%= f.submit "確認画面へ", class: "btn btn-lg btn-base-1 btn-primary mt-20" %>
                  </div>

                <% end %>
          </div>
        </div>

app/views/reviews/show.html.erb
<%= render 'layouts/header' %>



<div class="container">
  <div class="row col-md-offset-4 col-md-8 reviewnewtitle">
    <h4 style= "font-size: 25px"><%= @toy.manufacturer %>  <%= @toy.name %></h4>
  </div>

  <div class="row">

    <div class="col-md-offset-1 col-md-4 reviewnewtitle">

      <div class="a">
        <div class="b"><%= attachment_image_tag @toy, :toy1_image, format: 'jpeg', size: "300x300" %></div>
        <div class="b"><%= attachment_image_tag @toy, :toy2_image, format: 'jpeg', size: "300x300" %></div>
        <div class="b"><%= attachment_image_tag @toy, :toy3_image, format: 'jpeg', size: "300x300" %></div>
      </div>

    <br>

    <% if user_signed_in? %>
      <div class="toy-index-favorite">
        <% if @toy.toyfavorited_by?(current_user) %>
          <%= link_to toy_toyfavorites_path(@toy), method: :delete do %>
            <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
          <% end %>
        <% else %>
          <%= link_to toy_toyfavorites_path(@toy), method: :post do %>
            <i class="far fa-heart"></i>
          <% end %>
        <% end %>
        <%= @toy.toyfavorites.count %>
      </div>
    <% end %>

  </div>

  <div class="col-md-7">

    <table class="table toytable">
      <tbody>
        <tr>
          <th class="active">詳細情報</th>
          <th><%= @toy.name %></th>
        </tr>
        <tr>
          <th class="active">メーカー</th>
          <th><%= @toy.manufacturer %></th>
        </tr>
        <tr>
          <th class="active">商品名</th>
          <th><%= @toy.name %></th>
        </tr>
        <tr>
          <th class="active">アイテムジャンル</th>
          <th><%= @toy.genre.name %></th>
        </tr>
        <tr>
          <th class="active">価格</th>
          <th><%= @toy.price %></th>
        </tr>
        <tr>
          <th class="active">素材</th>
          <th><%= @toy.material %></th>
        </tr>
        <tr>
          <th class="active">商品の寸法(奥行きx幅x高さ)</th>
          <th><%= @toy.depth %><%= "x" %>
              <%= @toy.width %><%= "x" %>
              <%= @toy.height %></th>
        </tr>
        <tr>
          <th class="active">対象年齢</th>
          <th><%= @toy.target_yearage %><%= "歳" %>
              <%= @toy.target_monthage %><%= "歳ヶ月〜" %>
          </th>
        </tr>
        <tr>
          <th class="active">商品説明</th>
          <th><%= @toy.toy_introduction %></th>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<br><br>

<div class="col-md-12 searchfield">


  <div class="reviewarea">
    <div class="col-md-2 review-user">
      <%= attachment_image_tag @review.user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %><br>
      <p><%= @review.user.name %>さん</p>
    </div>
    <div class="col-md-10 review-toy">
      <div class="reviewscontent">
        <div class="reviewscontenthead">
          <p class="reviewday" style="font-size: 10px"><%= @review.created_at.strftime('%Y/%m/%d') %></p>
          <span style="font-size: 10px">使用したお子様の情報:　</span>
            <% if @review.child.sex == 1 %>
              <%= "男の子 " %><i class="fas fa-male " style="color: #68a4d9"></i>   |
            <% else %>
              <%= "女の子 " %><i class="fas fa-female" style="color: #e95388"></i>   |
            <% end %>
              <%= @review.age_year %>歳<%= @review.age_month %>ヶ月     |
              <%= @review.temperaments.pluck(:name).join(" ・") %>
        </div><br>
        <div class="col-md-4 reviewstoy">
          <%= link_to toy_path(@review.toy.id) do %>
            <%= attachment_image_tag @review.toy, :toy1_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %><br>
          <% end %>
          <p style="font-size: 10px"><%= @review.toy.name %></p><br>
        </div>
        <div class="col-md-8">
            <%= @review.rate %>点
            <!--星評価-->
            <div id="star-rate-<%= @review.id %>"></div>
            <script>
              $('#star-rate-<%= @review.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= @review.rate %>,
              });
            </script>
            <!--/星評価-->

          <br><br><p style="font-size: 10px"><%= @review.body %></p><br>

          <% if user_signed_in? %>
            <% unless @review.user == current_user %>
              <% if @review.reviewfavorited_by?(current_user) %>
                <%= link_to toy_review_reviewfavorites_path(@review.toy, @review), method: :delete do %>
                  参考になった！<i class="fas fa-thumbs-up"></i>
                  <%= review.reviewfavorites.count %>
                <% end %>
              <% else %>
                <%= link_to toy_review_reviewfavorites_path(@review.toy, @review), method: :post do %>
                  参考になった！<i class="far fa-thumbs-up"></i>
                  <%= @review.reviewfavorites.count %>
                <% end %>
              <% end %>
            <% else %>
              参考になった！<i class="fas fa-thumbs-up"></i><%= @review.reviewfavorites.count %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>