config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users, only: [:show, :edit, :update]
resources :toys do
  get :toysnologin
	resource :toyfavorites, only: [:create, :destroy]
	resources :reviews do
    get :myreview
		resource :reviewfavorites, only: [:create, :destroy]
		collection do
      		post :confirm
    	end
    end
end
resources :genres, only: [:new, :index, :create, :edit, :update]
resources :children, only: [:index, :show, :new, :create, :edit, :update]
resources :child_archives, only: [:index, :show, :new, :create, :edit, :update]
resources :effects, only: [:new, :index, :create, :edit, :update]
resources :temperaments, only: [:new, :create, :edit, :update, :index]

get 'homes/about'
root 'homes#top'


end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/child.rb
class Child < ApplicationRecord

belongs_to :user
attachment :profile_image
has_many :child_archives, dependent: :destroy
accepts_nested_attributes_for :child_archives
has_many :child_temperaments, dependent: :destroy
has_many :temperaments, through: :child_temperaments
accepts_nested_attributes_for :child_temperaments, allow_destroy: true
has_many :reviews, dependent: :destroy

validates :name, presence: true
validates :sex, presence: true
validates :age_year, presence: true, numericality: { only_integer: true }
validates :age_month, presence: true, numericality: { only_integer: true }
validates :temperament_ids, presence: true
validates :favorite_thing, presence: true
validates :un_favorite_thing, presence: true
validates :status, presence: true


def self.search(search)
    if search
       where(['name LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
    else
       all #全て表示させる
    end
end

default_scope -> { order(created_at: :desc) }


end

app/models/child_archive.rb
class ChildArchive < ApplicationRecord
	attachment :profile_image
	belongs_to :child
	belongs_to :user
	has_many :child_archive_temperaments, dependent: :destroy
	has_many :temperaments, through: :child_archive_temperaments
	accepts_nested_attributes_for :child_archive_temperaments, allow_destroy: true

	validates :age_year, presence: true, numericality: { only_integer: true }
	validates :age_month, presence: true, numericality: { only_integer: true }
	validates :name, presence: true
	validates :favorite_thing, presence: true
	validates :un_favorite_thing, presence: true
	validates :status, presence: true



	def self.search(search)
	    if search
	       where(['name LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
	    else
	       all #全て表示させる
	    end
 	end

 	default_scope -> { order(created_at: :desc) }



end

app/models/destroy.rb
class Destroy < ApplicationRecord
end

app/models/effect.rb
class Effect < ApplicationRecord
	has_many :reviews, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
  	belongs_to :toy
  	belongs_to :effect
  	belongs_to :child
  	has_many :reviewfavorites, dependent: :destroy
    has_many :liked_reviews, through: :reviewfavorites, source: :user
    has_many :review_temperaments, dependent: :destroy
    has_many :temperaments, through: :review_temperaments
    accepts_nested_attributes_for :review_temperaments, allow_destroy: true


    validates :body, presence: true
    validates :effect_id, presence: true
    validates :rate, presence: true
    validates :age_year, presence: true
    validates :age_month, presence: true


	def reviewfavorited_by?(user)
    reviewfavorites.where(user_id: user.id).exists?
  end


  	validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true

  default_scope -> { order(created_at: :desc) }

end

app/models/reviewfavorite.rb
class Reviewfavorite < ApplicationRecord

	belongs_to :user
	belongs_to :review

end

app/models/temperament.rb
class Temperament < ApplicationRecord
	has_many :child_temperaments
	has_many :children, through: :child_temperaments
	has_many :child_archive_temperaments
	has_many :child_archives, through: :child_archive_temperaments
	has_many :review_temperaments
	has_many :reviews, through: :review_temperaments

end

app/models/toy.rb
class Toy < ApplicationRecord
	attachment :toy1_image
	attachment :toy2_image
	attachment :toy3_image
	attachment :toy4_image
	belongs_to :genre
	has_many :reviews, dependent: :destroy
	has_many :toyfavorites, dependent: :destroy
	has_many :liked_toys, through: :toyfavorites, source: :user

	def toyfavorited_by?(user)
    toyfavorites.where(user_id: user.id).exists?
  	end


	def self.search(search)
	    if search
	       where(['name LIKE ? OR manufacturer LIKE ? OR material LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
	    else
	       all #全て表示させる
	    end
 	end

end

app/models/toyfavorite.rb
class Toyfavorite < ApplicationRecord

	belongs_to :user
	belongs_to :toy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  validates :place, presence: true
  validates :sex, presence: true
  validates :email, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :children, dependent: :destroy
  has_many :child_archives, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :toyfavorites, dependent: :destroy
  has_many :liked_toys, through: :toyfavorites, source: :toy
  has_many :reviewfavorites, dependent: :destroy
  has_many :liked_reviews, through: :reviewfavorites, source: :review





end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if review.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background-color: white">
<div class="container">
<header>
	<nav class="nav navbar-nav navbar-left">
		<span></span>
 	</nav>

 	<% if user_signed_in? %>

 	<nav>

		<ul class="nav navbar-nav navbar-left" >
			<div class="logo">
				<%= link_to root_path do %>
					<%= image_tag "logo.jpg", size: "95x69" %>
				<% end %>
			</div>
 		</ul>


		<ul class="nav navbar-nav navbar-right">

 			<li></li>

			<li>
				<%= link_to homes_about_path do %>
					<span class="fas fa-question-circle"></span>
						み〜つけたの特徴と使い方
				<% end %>
			</li>

			<li>
				<%= link_to root_path(anchor: 'ranking') do %>
					<%= image_tag('王冠のアイコン素材.png') %>
						ランキング
				<% end %>
			</li>

			<li>
				<%= link_to toy_reviews_path(1) do %>
					<%= image_tag('虫眼鏡アイコン9.png') %>
						口コミを探す
 				<% end %>
			</li>

			<li>
				<%= link_to toys_path do %>
 					<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
						口コミする
					</span>
				<% end %>
			</li>

			<li>
				<%= link_to user_path(current_user) do %>
					<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
 						マイページ
					</span>
				<% end %>
			</li>

			<li>
				<%= link_to child_archives_path do %>
 					<span class="glyphicon glyphicon-book" aria-hidden="true"></span>
						おもいで
					</span>
				<% end %>
			</li>

			<li>
				<%= link_to destroy_user_session_path, method: :delete do %>
 					<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
						ログアウト
					</span>
 				<% end %>
			</li>
		</ul>


<% else %>


	<ul class="nav navbar-nav navbar-left" >

		<div class="logo">
			<%= link_to root_path do %>
				<%= image_tag "logo.jpg", size: "95x69" %>
			<% end %>
 		</div>

	</ul>

	<ul class="nav navbar-nav navbar-right" >

		<li></li>

		<li>
			<%= link_to homes_about_path do %>
				<span class="glyphicon glyphicon-link" aria-hidden="true">
					ABOUT
				</span>
			<% end %>
		</li>

		<li>
			<%= link_to toy_toysnologin_path(1) do %>
				<span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
					口コミを見る
				</span>
			<% end %>
		</li>

		<li>
			<%= link_to new_user_registration_path do %>
				<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
					新規登録
				</span>
			<% end %>
		</li>

		<li>
			<%= link_to new_user_session_path do %>
				<span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
 					ログイン
				</span>
			<% end %>
		</li>
	</ul>

</nav>
<% end %>

</header>
</header>
</div>

<body>
<%= yield %>
</body>

app/views/layouts/_profile.html.erb
<table class="table">

  <div class="col-md-12 prof-name">
    <%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
  </div>

  <div class="col-md-12 prof-name">
    <%= user.name %>さん<br><br>
    <div class="proffavorite">いいねしたおもちゃ</div><%= user.toyfavorites.count %>
      <div class="proffavorite">いいねした口コミ</div><%= user.reviewfavorites.count %>
        <div class="proffavorite">いいねされた口コミ</div><%= @reviews.count %>
        </div>
        <tbody>
          <tr>
            <th class="active" style="font-size: 9px;">趣味</th>
            <th><%= user.hobby %></th>
          </tr>
          <tr>
            <th class="active" style="font-size: 9px;">都道府県</th>
            <th><%= user.place %></th>
          </tr>
          <tr>
            <th class="active" style="font-size: 9px;">自己紹介</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiTsuketa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>


  </head>

  <body>
    <div class="container">
    <% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
  <% end %>
  </body>

<%= yield %>
  </body>
</html>